In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing,linear_model
from sklearn.model_selection import train_test_split
%matplotlib inline

In [12]:
data = pd.read_csv('cotton.csv', sep=",", header=None)
data.columns = ["Rainfall", "Soil Moisture", "Temperature", "Yield"]
data.head()

Rainfall  Soil Moisture  Temperature  Yield
0    650.00          0.177        24.33    416
1    700.55          0.172        23.80    729
2    855.81          0.152        23.86    531
3    467.60          5.814        23.71    625
4   1148.85          2.031        24.12    603

In [13]:
X = np.array(data[["Rainfall","Soil Moisture","Temperature"]])
y = np.array(data["Yield"])
# X = preprocessing.scale(X)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
y_test

array([615, 626, 721, 603, 545, 279, 422, 333, 450, 550, 424, 708, 214,
       633, 519, 656, 615, 388, 169, 702])

In [14]:
X_train.shape
y_train.shape

(76,)

In [15]:
from sklearn import linear_model
clf = linear_model.LinearRegression()
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
pred = clf.predict(X_test)
clf.predict(X_test)
# clf.score(X_test,y_test)

array([ 516.13817408,  508.7809041 ,  489.51074641,  496.7382669 ,
        513.66715002,  507.10677569,  491.08534432,  488.13440062,
        507.4006503 ,  496.40600688,  525.66725878,  506.55869126,
        509.37658165,  512.19943402,  499.01999643,  506.33026027,
        524.60655627,  501.20023816,  515.54234824,  513.16918599])

In [17]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
X_ = poly.fit_transform(X_train)
predict = poly.fit_transform(y_train.reshape(1,-1))
predict

array([[  1.00000000e+00,   4.36000000e+02,   6.18000000e+02, ...,
          3.49281000e+05,   1.19382000e+05,   4.08040000e+04]])

In [18]:
clf = linear_model.LinearRegression()
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
clf.predict(X_test)

array([ 480.72637939,  512.45147029,  503.39558603,  474.87938264,
        548.19202697,  503.70315058,  508.93643241,  504.50915166,
        516.22712766,  483.90450828,  448.72336182,  511.72780103,
        484.67501337,  453.15740003,  478.84902415,  500.37930608,
        524.71631388,  465.9517165 ,  574.24064577,  507.86721393])